"""Generated summaries: synopsis, beat list, and candidate loglines.

**This is not part of the linter and never becomes a Finding.** Everything in
this file is model output, which means it cannot be checked against the page,
which means it fails the test every other number in this project has to pass.
It lives here, behind its own command, labelled as generated, so that the line
stays visible: `sluglint lint` and `sluglint stats` say only things a reader
can verify by hand, and `sluglint logline` says something a reader has to judge.

Why it exists anyway: a synopsis and a few candidate loglines are the first
thing anybody asks a screenplay for, and having the tool produce a draft the
writer then rewrites is honest work as long as nobody pretends it is a
measurement.

**Why an API model rather than a local summariser.** A local BART or Pegasus
checkpoint is trained on news wire and produces news-wire sentences from
screenplay input, it caps out around a thousand tokens of context so a feature
has to be chopped into eighty pieces, and it drags in several gigabytes of
torch for a feature that runs once per draft. The map-reduce below is the same
shape a local summariser would need and would work against one; what it would
not be is better.

**The cost is paid once.** Results are cached on a hash of the script text plus
the model and the number of candidates, so a re-run is free and a rewrite of
one scene is the only thing that invalidates it. That is the offloading: the
expensive pass happens once, the candidates are then a file on disk.
"""
from __future__ import annotations

import hashlib
import json
import os
from dataclasses import asdict, dataclass, field
from pathlib import Path

from .models import Script

DEFAULT_MODEL = os.environ.get("SLUGLINT_MODEL", "claude-sonnet-5")
CACHE_DIR = Path(os.environ.get("SLUGLINT_CACHE", Path.home() / ".cache" / "sluglint"))
SCENES_PER_CHUNK = 25
MAX_TOKENS = 4000

DIGEST_SCHEMA = {
    "type": "object",
    "properties": {
        "summary": {"type": "string",
                    "description": "What happens in these scenes, in 4 sentences or fewer."},
        "threads": {"type": "array", "items": {"type": "string"},
                    "description": "Situations opened or closed here, one clause each."},
    },
    "required": ["summary", "threads"],
    "additionalProperties": False,
}

RESULT_SCHEMA = {
    "type": "object",
    "properties": {
        "synopsis": {"type": "string", "description": "One paragraph, present tense."},
        "beats": {"type": "array", "items": {"type": "string"},
                  "description": "The turning points in order, one line each."},
        "loglines": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "text": {"type": "string"},
                    "angle": {"type": "string",
                              "description": "What this version leads with."},
                },
                "required": ["text", "angle"],
                "additionalProperties": False,
            },
        },
    },
    "required": ["synopsis", "beats", "loglines"],
    "additionalProperties": False,
}

MAP_SYSTEM = """You are summarising consecutive scenes of a screenplay for a writer's \
own reference. Report only what happens on the page. Do not evaluate, do not praise, \
do not speculate about intent, and do not invent detail that is not in the text."""

REDUCE_SYSTEM = """You write coverage-desk summaries of screenplays from scene digests.

Rules:
- Present tense, third person, no adjectives of judgement. Never say the script is
  good, bad, commercial, or moving.
- The synopsis is one paragraph and describes what happens, including the ending.
- Beats are the turning points in order, one line each.
- Each logline is one or two sentences and leads with a DIFFERENT angle from the
  others: the protagonist's problem, the situation, the antagonist, the world, the
  ironic reversal. Say what the angle is.
- Use only what the digests contain. If something is not in them, leave it out."""


@dataclass
class Logline:
    text: str
    angle: str = ""


@dataclass
class Summary:
    """Model output about one script. Generated, not measured."""
    title: str
    model: str
    script_hash: str
    synopsis: str = ""
    beats: list[str] = field(default_factory=list)
    loglines: list[Logline] = field(default_factory=list)
    generated: bool = True          # always true; here so the JSON says so

    def to_dict(self) -> dict:
        d = asdict(self)
        d["disclaimer"] = (
            "Generated by a language model from the script text. Unlike every other "
            "number this tool reports, nothing here can be checked against the page. "
            "Treat it as a first draft to rewrite.")
        return d


def _fingerprint(script: Script, model: str, n: int) -> str:
    body = script.raw_text or "\n".join(el.text for el in script.elements)
    return hashlib.sha256(f"{model}|{n}|{body}".encode()).hexdigest()[:24]


def cache_path(script: Script, model: str, n: int) -> Path:
    return CACHE_DIR / f"logline-{_fingerprint(script, model, n)}.json"


def load_cached(script: Script, model: str = DEFAULT_MODEL, n: int = 3) -> Summary | None:
    path = cache_path(script, model, n)
    if not path.is_file():
        return None
    data = json.loads(path.read_text(encoding="utf-8"))
    return Summary(
        title=data.get("title", ""), model=data.get("model", model),
        script_hash=data.get("script_hash", ""), synopsis=data.get("synopsis", ""),
        beats=list(data.get("beats", [])),
        loglines=[Logline(**item) for item in data.get("loglines", [])],
    )


def _store(summary: Summary) -> Path:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    path = CACHE_DIR / f"logline-{summary.script_hash}.json"
    path.write_text(json.dumps(summary.to_dict(), indent=2, ensure_ascii=False),
                    encoding="utf-8")
    return path


def _chunks(script: Script):
    for i in range(0, len(script.scenes), SCENES_PER_CHUNK):
        yield script.scenes[i:i + SCENES_PER_CHUNK]


def _call(client, model: str, system: str, user: str, schema: dict) -> dict:
    resp = client.messages.create(
        model=model,
        max_tokens=MAX_TOKENS,
        system=system,
        # Same reasoning as tier 3: max_tokens caps thinking and output together,
        # and a truncated JSON body is worse than a shallower answer.
        thinking={"type": "disabled"},
        output_config={"effort": "low",
                       "format": {"type": "json_schema", "schema": schema}},
        messages=[{"role": "user", "content": user}],
    )
    text = "".join(b.text for b in resp.content if getattr(b, "type", "") == "text")
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return {}


def generate(script: Script, model: str = DEFAULT_MODEL, n: int = 3,
             refresh: bool = False) -> tuple[Summary | None, list[str]]:
    """-> (summary, notices). Never raises on a missing key; returns a notice."""
    if not refresh and (cached := load_cached(script, model, n)):
        return cached, [f"Loaded from cache ({cache_path(script, model, n)})."]
    if not os.environ.get("ANTHROPIC_API_KEY"):
        return None, ["Set ANTHROPIC_API_KEY to generate summaries. "
                      "Every other command runs without it."]
    try:
        import anthropic  # noqa: PLC0415 - optional dependency, imported on demand
    except ImportError:
        return None, ["`pip install 'sluglint[llm]'` to generate summaries."]
    if not script.scenes:
        return None, ["Nothing to summarise: no scenes parsed."]

    client = anthropic.Anthropic()
    notices: list[str] = []
    digests: list[dict] = []

    # Map: one pass per block of scenes, so a feature fits whatever the context
    # window is and each call sees a coherent stretch rather than a slice.
    for chunk in _chunks(script):
        body = "\n\n".join(f"--- SCENE {s.index + 1} | {s.heading} ---\n{s.text}"
                           for s in chunk)
        try:
            digest = _call(client, model, MAP_SYSTEM,
                           f"SCENES {chunk[0].index + 1} to {chunk[-1].index + 1}:\n\n{body}",
                           DIGEST_SCHEMA)
        except Exception as exc:                     # noqa: BLE001 - report, do not crash
            notices.append(f"Digest failed for scenes "
                           f"{chunk[0].index + 1}-{chunk[-1].index + 1}: {exc}")
            continue
        if digest.get("summary"):
            digests.append({"scenes": f"{chunk[0].index + 1}-{chunk[-1].index + 1}", **digest})

    if not digests:
        return None, notices + ["No digests were produced; nothing to reduce."]

    # Reduce: one pass over the digests, which is where the whole shape of the
    # script is visible at once and where the candidates have to differ.
    cast = ", ".join(c for c, _ in sorted(script.character_registry().items(),
                                          key=lambda kv: -len(kv[1]))[:12])
    rolled = "\n\n".join(
        f"SCENES {d['scenes']}\n{d['summary']}\nOpen or closed here: "
        f"{'; '.join(d.get('threads', []))}" for d in digests)
    user = (f"TITLE: {script.title or 'untitled'}\nPRINCIPAL CAST: {cast or 'unknown'}\n"
            f"SCENES: {len(script.scenes)}\n\nDIGESTS:\n{rolled}\n\n"
            f"Produce a synopsis, the beats in order, and exactly {n} loglines, "
            f"each leading with a different angle.")
    try:
        result = _call(client, model, REDUCE_SYSTEM, user, RESULT_SCHEMA)
    except Exception as exc:                         # noqa: BLE001 - report, do not crash
        return None, notices + [f"Summary call failed: {exc}"]

    summary = Summary(
        title=script.title or Path(script.path).stem,
        model=model,
        script_hash=_fingerprint(script, model, n),
        synopsis=str(result.get("synopsis", "")),
        beats=[str(b) for b in result.get("beats", [])],
        loglines=[Logline(text=str(item.get("text", "")), angle=str(item.get("angle", "")))
                  for item in result.get("loglines", [])][:n],
    )
    notices.append(f"Cached at {_store(summary)}.")
    return summary, notices


def render_console(summary: Summary) -> str:
    out = [
        f"Sluglint summary: {summary.title}",
        f"GENERATED by {summary.model}. Unlike everything else this tool prints,",
        "nothing below can be checked against the page. It is a draft to rewrite.",
        "=" * 72, "",
        "SYNOPSIS", "",
    ]
    out += ["  " + line for line in _wrap(summary.synopsis)]
    if summary.beats:
        out += ["", "BEATS", ""]
        out += [f"  {i:>2}. {b}" for i, b in enumerate(summary.beats, start=1)]
    if summary.loglines:
        out += ["", f"LOGLINES ({len(summary.loglines)} versions, different angles)", ""]
        for i, lg in enumerate(summary.loglines, start=1):
            out.append(f"  {i}. [{lg.angle}]")
            out += ["     " + line for line in _wrap(lg.text)]
    return "\n".join(out)


def _wrap(text: str, width: int = 70) -> list[str]:
    words, lines, current = text.split(), [], ""
    for word in words:
        if len(current) + len(word) + 1 > width:
            lines.append(current)
            current = word
        else:
            current = f"{current} {word}".strip()
    if current:
        lines.append(current)
    return lines or [""]
